apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::481155270892:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-k4X0fhsWKUjV
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::481155270892:user/vsks
      username: vsks
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-01T10:12:24Z"
  name: aws-auth
  namespace: kube-system
  uid: 7e26850b-07e5-4761-acd0-7ba47b3cce72
